name: build-and-deploy

on: [push,pull_request]

concurrency:
  group: ${{ github.action == 'build-and-deploy' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  build-and-push-to-gcr:
    name: 'Build and push docker image'
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY_ENC }}
          registry: gcr.io
          project_id: takehomeproject-tomtar
          image_name: nestjs-realworld-example-app
          image_tag: latest
          dockerfile: ./Dockerfile

  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Terraform Plan
        continue-on-error: true
        run: |
          cd terraform
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_validate.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/tf_validate.sh"
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_plan_check.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/tf_plan_check.sh"
          terraform plan -out "tf_plan" -input=false
          cd .. && mv terraform/tf_plan .

      - name: Upload TF Plan
        uses: actions/upload-artifact@v3
        with:
          name: tf_plan
          path: ./tf_plan
          if-no-files-found: error
          retention-days: 1

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Download TF Plan
        uses: actions/download-artifact@v2
        with:
          name: tf_plan
          path: .

      - name: Terraform Apply
        run: |
          mv tf_plan terraform && cd terraform
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/tf_init.sh"
          terraform show "tf_plan"
          terraform apply "tf_plan"
